### ISSUE TITLE
OrbitDB Provider MVP

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/js-uprtcl#136]
# Spec

## Overview

The goal of the activity is to develop an "Evees Provider" that stores and govern_Prtcl Evees on OrbitDB.

The core of the work consists on developing a Typescript class `EveesOrbitDB`, which implements the [`EveesRemote`](https://github.com/uprtcl/js-uprtcl/blob/develop/modules/evees/src/services/evees.remote.ts) and [`Authority`](https://github.com/uprtcl/js-uprtcl/blob/develop/modules/access-control/src/types/authority.ts#L1) interfaces, in a new `orbitdb` folder created under `/modules/evees/src/services/providers`

In general, it should be a class equivalent to [`EveesEthereum`](https://github.com/uprtcl/js-uprtcl/blob/develop/modules/evees/src/services/providers/ethereum/evees.ethereum.ts), but replacing all the dependencies on Ethereum with dependencies on OrbitDB. 

The expected components of this class will be:

- A connection to an [orbitdb-http-api](https://github.com/orbitdb/orbit-db-http-api) to interact with OrbitDB.
- All the required methods of the `EveesRemote` interface including:
    - `cloneAndInitPerspective(newPerspectiveData: NewPerspectiveData)`: Which should create a new perspective "owned" (owned = only that user can update its "details") by the `newPerspectiveData.owner` userid. The method should:
        - store the `newPerspectiveData.perspective` object into IPFS (it could use our [ipfsStore](https://github.com/uprtcl/js-uprtcl/blob/fca80941afca0df57b3c1b3c83c6e7a41088e6e3/providers/ipfs/src/ipfs.store.ts#L22) as it's done by `EveesEthereum`).
        - set the perspective details (`headId` and `context`) as specified in `newPerspectiveData.details` (it can ignore the `name` field, and one or both can be `undefined`)
    - `clonePerspectivesBatch()` which can be an iterator calling `cloneAndInitPerspective` multiple times.
    - `clonePerspective(secured: Secured<Perspective>)` which dont need to be implemented.
    - `cloneCommit(secured: Secured<Commit>):` which dont need to be implemented.
    - `updatePerspectiveDetails(perspectiveId: string, details: PerspectiveDetails)`: which should update the perspective `headId` and/or `context`.
    - `getContextPerspectives(_context: string)`: which should return all perspectives whose `context` matches the input `_context`.
    - `getPerspectiveDetails(perspectiveId: string)`: which should return the current/latest `headId` and `context` of a given perspective.
    - `deletePerspective(perspectiveId: string)`: which should set the `context` and `headId` to empty strings.
- All the required methods of the `Authority` interface:
    - isReady(): which should be a resolved promise when the OrbitDB connection is ready.
    - login: which can be used if the users needs to login to OrbitDB (maybe signing a deterministic message with metamask and storing that signature as private key if that ethereum user in OrbitDb)
    - isLogged(): which should be true if the login method is used and the privatekey is already saved.
    - logout(): which should delete the private key from browser storage.

## User Story

Once the `EveesOrbitDB` class and connection are ready, we will be able to update our test application (a multi-perspective wiki) by replacing the `EveesHttp` class on the [demo app configuration](https://github.com/uprtcl/js-uprtcl/blob/develop/demos/simple-editor/src/index.js#L56) with an `EveesOrbitDB` class and the wiki app will replace the HTTP server with OrbitDB.

This means that the user will be able to "log in" into OrbidDB by signing a deterministic private message derived from its ethereum account. 

The message can be `My OrbitDB Evees Provider` and it's signature can be used as the private key of the user on OrbitDB **(TBC if this makes sense)**.

Then the user will create a new perspective, which will clone the current content of the Wiki on Ethereum, will be able to edit it (creating and editing pages), and will be able to propose an update to the Ethereum perspective of the Wiki. Note all this is done by `js-uprtcl` and need not be coded as part of this contract. As long as the OrbitDB works as expected, this user flow should also work as expected.

In case there are issues found trying to recreate this process, the EveesOrbitDB, and its connection may have to be reviewed until we make it work.

**Comment by tabcat** [comment]
It's been delivered, tested, and accepted. Thank you @pepoospina for working with me through this, it was  a pleasure. I look forward to providing assistance building the orbit-db infrastructure for high availability of content.

**Comment by pepoospina** [comment]
Thank you @tabcat . Excellent work!
