### ISSUE TITLE
Perspective Ecosystem

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/js-uprtcl#195]
Perspective Ecosystem

The perspective ecosystem is the set of all the descendants of a perspective plus the perspective itself. The descendants include the children of the perspective, as long as the children of the children.

The [figure below](https://docs.google.com/drawings/d/1wUU63fWK5aM_nM-nYaULXV1euLeOSxh3vbfwRW815N0/edit) shows a tree of perspectives and highlight the ecosystem of some of them.

![img](https://docs.google.com/drawings/d/e/2PACX-1vT0PDAIKRw33QqVBMNCHRlkuRZM00v6B_ZSG7OPZhgcUrHRUCJvpFLdL1W7XnwisOtlvSiYlBp1DvsN/pub?w=1362&h=921)

In order to keep the links from the perspective ot its ecosystem, an edge (and its reverse) must be kept from the perspective from each element in the ecosystem. These edges are derived from the children of the perspective and can change every time the perspective updates.

As you can see, one perspective can be in the ecosystem of many other perspectives contemporary.

## Derive the perspective children

To derive the children of a perspective, it's data object must be processed. However, we want to store different data structures and, thus, it is not possible to get the children of an object directly from it. 

For example, the children of a [TextNode](https://github.com/uprtcl/js-uprtcl/blob/720ac06b4caf16b5d2bc6de57e042cb6546fab6f/modules/documents/src/types.ts#L9) are under the "links" property, however, the children of a [Wiki](https://github.com/uprtcl/js-uprtcl/blob/a2b161540ebe0a31edd13aa7de888c56add19e8a/modules/wikis/src/types.ts) object are derived from its pages property. 

In general, the children of an object will be identifiers to other objects and can be found anywhere inside that object, they don't need to be grouped on a single array.

We use Cortex Patterns to derive the children of an object without knowing in advance what that object is. This means that we will, for the first time, use frontend libraries in the backend.

In order to use Cortex patterns, we need to

- Create/Initialize a pattern registry service.
- Fill the pattern registry with the patterns that the application (in this case the backend) will understand.
- When wanting to read or update the children of an object, use the `getChildren` and `setChildren` pattern of that object.

So, what we need to do is to add logic to the `updatePerspective()` method of the uprtcl.service, so that it keeps an array of ecosystem edges from the perspective to all its descendants and itself, and to add logic that will keep updated these edges every time the perspective content is updated. 

This means:
- Every time a new child is added, that child and all its ecosystem must be added as the ecosystem of the perspective.
- Every time an existing child is removed, that element and all its ecosystem must be removed from the ecosystem of the perspective. 
  
Subtasks are then:

- [x] in `updateHead()` add `getPerspectiveData function to `UprtclService` that gets current data. Get old data and new data
- [x] derive the added children and the deleted children
- [x] update the ecosystem of perspectiveId accordingly.

**Comment by pepoospina** [comment]
To start, just patch the Pattern recognizer with a hardcoded if on the data object structure

```
if (data.links !== undefined) {
      children = data.links;
    } else if (data.pages !== undefined) {
      children = data.pages;
    }
```

**Comment by sotous** [comment]
Hi there!, already finished the perspective ecosystem feature, if you guys want to catch up with it. https://github.com/uprtcl/js-uprtcl-server/pull/25
