### ISSUE TITLE
Get independent other perspectives

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/js-uprtcl#199]
Add a function inside `uprtcl.repository.ts` that will return the "other independent perspectives" of one perspective.

The other independent perspectives of a perspective A, for example, are those other perspectives having the same `context` than perspective A, and not having a `parent` that has the same `context` as the `context` of the current UI parent of perspective A.

We will need to use the `~children` reverse edge ([this issue](https://github.com/uprtcl/js-uprtcl/issues/200)) to get the parent perspectives of a given perspective.

![](https://docs.google.com/drawings/d/e/2PACX-1vR8S0nh8WTLQ_7XompP3pHCw37qv5r4h8HRtuagLYgvOmLn04UVxS-nIuVaJMJI_spApex-FzcYCaDy/pub?w=1095&h=498&a=2)

**Comment by sotous** [comment]
So here we have the PR regarding this issue: https://github.com/uprtcl/js-uprtcl-server/pull/31
