### ISSUE TITLE
Add children edges (and reverse)

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/js-uprtcl#200]
We need to keep, next to the ecosystem edges the children edges.

The children edges refer to the immediate children of an object, this, the ecosystem edges can be seen as a redundant cache of the join of all the recursive children of an object, plus the object itself.

The children edges should be kept updated together with the ecosystem edges, as they usually change together.

The should also keep a @reverse annotation so that its supper gast to get the all the parent object sof an object.

**Comment by sotous** [comment]
https://github.com/uprtcl/js-uprtcl-server/pull/29
