### ISSUE TITLE
Deploy on AWS and SlashGraphql

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/js-uprtcl#227]
- [x] Deploy the backend server on AWS (update the current lambda function)
- [x] Connect dgraph on slash gql
- [x] Deploy de frontend at demo.intercreativity.io (similar to eth.intercreativity.io)

**Comment by pepoospina** [comment]
@sotous you can check [this video](https://drive.google.com/drive/u/0/folders/1IeB512UW-Q2X_BjHw2dtomKUXIVV21Nw) to understand how AWS is configured.

**Comment by sotous** [comment]
Hey there, you can already try out the demo, is online and deployed. I would love to have a meeting to explain what has been done for the deploy to work.
